### ISSUE TITLE
Poor Alignment of Search Bar Placeholder and Search Icon

### ISSUE THREAD

**Issue by jaitensahu** [0silverback0/LandingPages#50]
Description:

Issue: I came across an alignment issue in the repository's search bar. The placeholder text and the search icon are not aligned correctly, which affects the user experience and the overall aesthetics of the search functionality.

Steps to Reproduce:

Visit the Lioness Project.
Focus on the search bar, and you will notice that the placeholder text and the search icon are misaligned.

Expected Behavior:
The placeholder text and the search icon should be properly aligned within the search bar, creating a visually pleasing and user-friendly appearance.

Actual Behavior:
The placeholder text appears to be misaligned with the search icon, which affects the visual consistency and user experience.

https://github.com/0silverback0/LandingPages/assets/127736781/f861c013-09fb-4a1d-9e4a-bc6131a63397

**Comment by jfhgshg** [comment]
I want to work on this issue. Please assign this issue to me

**Comment by 0silverback0** [comment]
Good attention to detail! Thanks for the detailed description also @jaitensahu

**Comment by jaitensahu** [comment]
Hi @0silverback0 thank you for assigning me. I think that another contributor has submitted a pull request (PR) addressing the issue we were working on. The PR is ready for review and appears to meet the requirements.

Please take a look at the PR whenever you have a chance and consider merging it if it aligns with our project's standards and goals. This would help move things forward and ensure that the issue is resolved promptly.

**Comment by 0silverback0** [comment]
now that i look at it i dont see the search bar anymore.

**Comment by 0silverback0** [comment]
i did not merge that commit beacuse there was still an issue with it. I rather not have it all than have it not functioning correctly
